name: ESUG web site build

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ecstatic_build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y libasound2:i386 libssl1.0.0:i386 libfreetype6:i386

    - uses: actions/checkout@v2
      
    - name: Generate
      run: make generate

    - uses: actions/upload-artifact@v3
      with:
        name: ecstatic_site
        path: |
          _site
          !path/**/*.pillar
        retention-days: 5

  agenda_build:      
    uses: pillar-markup/Microdown-Agenda/.github/workflows/main.yml@main
    with:
      agenda_filename: agenda.md

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ecstatic_site

    - uses: actions/download-artifact@v3
      with:
        name: agenda
        path: _site/2022-Conference/agenda

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: _site # The folder the action should deploy.
      if: github.event_name != 'pull_request'
