name: ESUG web site build

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Generate
      run: make generate
      
    - name: Deploy
      run: make deploy
      if: github.ref == 'refs/heads/source' # only deploy on push
